#!/usr/bin/env python
"""One-off: build the frame_pdf.py manifest for the ADCC Trials Finals 2023-24 compilation.

Not a general tool -- this is glue for a single job. The reusable parts (transcript parsing,
bout-index parsing, gap-filling into fixed windows) live in ``scripts/frame_pdf.py`` and are
tested there; this script just calls them and writes the manifest JSON.

    uv run python scripts/build_trials_manifest.py

Writes ``data/frame_pdf/trials_2023_24_manifest.json``: the 6 complete-range bouts named in
the transcript's header index (fine step, 720p quality via ``kind: full_match``), followed by
the rest of the ~8.5h video sliced into 10-minute windows (coarse step, 480p via
``kind: full_event``) so no part of the video is dropped. Every entry carries
``transcript`` pointing at the same transcript file, which is how frame_pdf.py knows to print
captions beside each frame.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from scripts.frame_pdf import build_windows, hhmmss, parse_bout_index, probe  # noqa: E402

URL = "https://www.youtube.com/watch?v=pwGbW5GZgfc"
TRANSCRIPT = REPO / "data" / "frame_pdf" / "trials_2023_24_transcript.md"
OUT = REPO / "data" / "frame_pdf" / "trials_2023_24_manifest.json"
WINDOW_SECONDS = 600.0


def main() -> None:
    bouts = parse_bout_index(TRANSCRIPT)
    duration = float(probe(URL)["duration"])
    print(f"video duration: {hhmmss(duration)} ({duration:g}s); {len(bouts)} named bouts")

    rows: list[dict[str, object]] = []
    for label, start, end in bouts:
        rows.append({
            "url": URL, "start": start, "end": end, "label": label,
            "kind": "full_match", "transcript": str(TRANSCRIPT),
            "note": "ADCC Trials Finals 2023-24 compilation, named range from the header index",
        })

    windows = build_windows(bouts, duration, window=WINDOW_SECONDS)
    for ws, we in windows:
        rows.append({
            "url": URL, "start": ws, "end": we, "kind": "full_event",
            "transcript": str(TRANSCRIPT), "step": 20,
            "note": f"ADCC Trials Finals 2023-24 compilation, unindexed remainder "
                    f"{hhmmss(ws)}-{hhmmss(we)}, coarse locator window",
        })

    doc = {
        "_comment": [
            "ADCC Trials Finals 2023-24 compilation (pwGbW5GZgfc), 8h29m26s.",
            f"{len(bouts)} named bouts from the transcript header's complete ranges, fine "
            "step, full_match quality (720p). The remaining "
            f"{sum(1 for _ in windows)} rows are the unindexed remainder sliced into "
            f"{WINDOW_SECONDS:g}s windows, coarse step (20s), full_event quality (480p) -- "
            "so no part of the video is silently dropped.",
            "Generated by scripts/build_trials_manifest.py -- do not hand-edit; regenerate.",
        ],
        "videos": rows,
    }
    OUT.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT}: {len(bouts)} named bouts + {len(windows)} windows = {len(rows)} rows")


if __name__ == "__main__":
    main()
