#!/usr/bin/env python
"""One-off: build the frame_pdf.py manifest for the ADCC Trials Finals 2023-24 compilation.

Not a general tool -- this is glue for a single job. The reusable parts (transcript parsing,
window-filling, rendering) live in ``scripts/frame_pdf.py`` and are tested there; this script
just reads the curated bout index and writes the manifest JSON.

    uv run python scripts/build_trials_manifest.py

Source of truth is ``data/frame_pdf/trials_2023_24_bouts.json`` -- the CURATED index of all
52 bouts actually present in the video, derived 2026-08-25 by scoreboard-reading every frame
of the previous PDF set and cross-referencing the published finals results of all 8 trials
events in the 2023-24 cycle. It replaced the transcript header's 6-bout index + blind 600s
gap windows, which split fights across window PDFs and carried no athlete names.

Writes ``data/frame_pdf/trials_2023_24_manifest.json``: one ``full_match`` (720p) entry per
bout, labelled "A vs. B", with ``transcript`` attached so every frame carries its narration
window. No gap windows: the curated index covers the whole broadcast; the few uncovered
minutes are podiums/studio transitions with no match content.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from scripts.frame_pdf import hhmmss  # noqa: E402

TRANSCRIPT = REPO / "data" / "frame_pdf" / "trials_2023_24_transcript.md"
BOUTS = REPO / "data" / "frame_pdf" / "trials_2023_24_bouts.json"
OUT = REPO / "data" / "frame_pdf" / "trials_2023_24_manifest.json"


def main() -> None:
    idx = json.loads(BOUTS.read_text(encoding="utf-8"))
    url = idx["url"]
    rows: list[dict[str, object]] = []
    for bout in idx["bouts"]:
        note = f"{bout['event']} -- {bout['division']} final"
        if bout.get("note"):
            note += f" ({bout['note']})"
        rows.append({
            "url": url, "start": bout["start"], "end": bout["end"],
            "label": bout["label"], "kind": "full_match",
            "transcript": str(TRANSCRIPT), "note": note,
        })

    doc = {
        "_comment": [
            "ADCC Trials Finals 2023-24 compilation (pwGbW5GZgfc), 8h29m33s.",
            f"{len(rows)} bouts from the curated index trials_2023_24_bouts.json (scoreboard-"
            "verified, all athletes named), full_match quality (720p), transcript captions on "
            "every frame. No gap windows: the index covers the entire broadcast.",
            "Generated by scripts/build_trials_manifest.py -- do not hand-edit; regenerate.",
        ],
        "videos": rows,
    }
    OUT.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    span = sum(r["end"] - r["start"] for r in rows)  # type: ignore[operator]
    print(f"wrote {OUT}: {len(rows)} named bouts, {hhmmss(span)} of footage")


if __name__ == "__main__":
    main()
