"""Research-ground insights report — the exploration output.

Runs the network metrics (``analysis.network_metrics``) and fighter-similarity
(``analysis.fighter_similarity``) over the live corpus and writes a deterministic
**Markdown + JSON** report to ``docs/insights/`` for us to read and decide what's worth
turning into public content. This is an *internal* artifact — it writes nothing to the site.

    uv run python -m analysis.insights [--out docs/insights]
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

from analysis.fighter_similarity import athlete_style_vectors, nearest_in
from analysis.network_metrics import (
    build_transition_network,
    detect_communities,
    pagerank_ranking,
    reward_risk_ranking,
    route_to_submission,
)

logger = logging.getLogger(__name__)

_DEFAULT_OUT = Path(__file__).resolve().parents[1] / "docs" / "insights"
_NOTABLE = 6
_COMMUNITIES = 6


def generate_insights(session: Any) -> dict[str, Any]:
    """Compute the full insights payload from the DB (deterministic, no timestamps)."""
    g = build_transition_network(session)
    total_w = int(sum(d["weight"] for _, _, d in g.edges(data=True)))

    pagerank = [[n, s] for n, s in pagerank_ranking(g, 15)]
    rr_rows = reward_risk_ranking(g, min_occ=5, limit=15)
    reward_risk = [[n, rr, occ] for n, rr, occ in rr_rows]
    routes = {n: route_to_submission(g, n) for n, _, _ in rr_rows[:6]}
    communities = [
        {"size": len(c), "type_lead": _lead_type(g, c), "members": c[:12]}
        for c in detect_communities(g, min_occ=3)[:_COMMUNITIES]
    ]

    ids, mat = athlete_style_vectors(session)
    similarity = {nm: nearest_in(ids, mat, nm, 5) for nm in _notable_names(session, ids)}

    return {
        "network": {
            "nodes": g.number_of_nodes(),
            "edges": g.number_of_edges(),
            "transitions": total_w,
            "athletes_profiled": len(ids),
        },
        "pagerank": pagerank,
        "reward_risk": reward_risk,
        "routes": routes,
        "communities": communities,
        "similarity": similarity,
    }


def _lead_type(g: Any, members: list[str]) -> str:
    """Dominant technique type within a community (its 'flavour')."""
    from collections import Counter
    c: Counter[str] = Counter()
    for m in members:
        c[g.nodes[m].get("type", "")] += g.nodes[m].get("occ", 0)
    return c.most_common(1)[0][0] if c else ""


def _notable_names(session: Any, ids: list[tuple[str, str]]) -> list[str]:
    """Marquee athletes (top rank_elo) that we actually have a style vector for."""
    from sqlalchemy import select

    from db.models import Athlete

    present = {nm for _, nm in ids}
    names = session.execute(
        select(Athlete.name).where(Athlete.rank_elo.isnot(None)).order_by(Athlete.rank_elo.desc())
    ).scalars()
    out: list[str] = []
    for n in names:
        if n in present and n not in out:
            out.append(n)
        if len(out) >= _NOTABLE:
            break
    return out


# ── rendering ────────────────────────────────────────────────────────────────
def render_markdown(r: dict[str, Any]) -> str:
    net = r["network"]
    out: list[str] = [
        "# Grappling network — insights report",
        "",
        "_Generated by `analysis.insights` from the match corpus. Internal exploration "
        "artifact — not published. Reward-risk follows Lamas et al. 2024._",
        "",
        f"**Network:** {net['nodes']} positions · {net['edges']} transitions types · "
        f"{net['transitions']} total transitions · {net['athletes_profiled']} athletes profiled.",
        "",
        "## The hubs of grappling (PageRank)",
        "",
        "| # | Position | PageRank |",
        "|---|---|---|",
    ]
    out += [f"| {i+1} | {n} | {s:.4f} |" for i, (n, s) in enumerate(r["pagerank"])]
    out += [
        "",
        "## Reward-risk balance — P(finish) − P(get finished), by position",
        "",
        "_Positions seen ≥5×, best balance first._",
        "",
        "| # | Position | Reward-risk | Seen |",
        "|---|---|---|---|",
    ]
    out += [f"| {i+1} | {n} | {rr:+.3f} | {occ} |"
            for i, (n, rr, occ) in enumerate(r["reward_risk"])]
    out += ["", "## Highest-probability routes to a finish", ""]
    out += [f"- **{start}** → " + " → ".join(path[1:])
            for start, path in r["routes"].items() if len(path) > 1]
    out += ["", "## Game families (community detection)", ""]
    for i, c in enumerate(r["communities"], 1):
        out.append(f"**Family {i}** ({c['size']} positions, mostly _{c['type_lead']}_): "
                   + ", ".join(c["members"]) + ".")
        out.append("")
    out += ["## Fighter DNA — stylistically closest athletes", ""]
    for name, neighbours in r["similarity"].items():
        if neighbours:
            out.append(f"- **{name}**: " + ", ".join(f"{n} ({s:.2f})" for n, s in neighbours))
    out += [
        "",
        "---",
        "_Next: each section above is a candidate public content type — position map, "
        "reward-risk rankings, the families of grappling, 'fighters like X'. See "
        "`docs/graph_analysis_approaches.md`._",
    ]
    return "\n".join(out) + "\n"


def run(out: Path) -> int:
    from db.base import db_session

    out.mkdir(parents=True, exist_ok=True)
    with db_session() as session:
        report = generate_insights(session)
    (out / "insights.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "insights.md").write_text(render_markdown(report), encoding="utf-8")
    logger.info("Insights → %s (%d positions, %d athletes)",
                out, report["network"]["nodes"], report["network"]["athletes_profiled"])
    return 0


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass
    ap = argparse.ArgumentParser(description="Generate the graph-analysis insights report")
    ap.add_argument("--out", type=Path, default=_DEFAULT_OUT, help="output dir")
    return run(ap.parse_args().out)


if __name__ == "__main__":
    raise SystemExit(main())
